version: "3"
services:
  node:
    restart: always
    build: .
    ports:
      - 3000:3000
    environment:
      - ES_HOST=elasticsearch
      - ELASTIC_URL=http://elasticsearch:9200
    volumes:
      - ./:/code
    depends_on:
      - mongo
      - elasticsearch
    networks:
      - esnet
      - mongonet
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    networks:
      - mongonet
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
    # volumes:
    #   - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - xpack.security.enabled=$ELASTIC_SECURITY
    logging:
      driver: none
    ports:
      - 9200:9200
    networks:
      - esnet
  kib01:
    image: docker.elastic.co/kibana/kibana:7.0.1
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    depends_on:
      - elasticsearch
    networks:
      - esnet
volumes:
  mongodb:
  # esdata:

networks:
  esnet:
  mongonet:
